namespace TradeLike.Api.Contracts.Settings;

public sealed record BusinessSettingsResponse(
    int Id,
    string BusinessName,
    string? LegalName,
    string? LogoUrl,
    string? AddressLine1,
    string? AddressLine2,
    string? Town,
    string? County,
    string? Postcode,
    string? Country,
    string? Phone,
    string? Email,
    string? Website,
    string? VatNumber,
    decimal DefaultVatRate,
    string QuotePrefix,
    string InvoicePrefix,
    string? PaymentTerms,
    string? BankName,
    string? BankAccountName,
    string? BankSortCode,
    string? BankAccountNumber,
    string? EmailFooter,
    DateTime CreatedAt,
    DateTime? UpdatedAt
);

public sealed record UpdateBusinessSettingsRequest(
    string BusinessName,
    string? LegalName,
    string? LogoUrl,
    string? AddressLine1,
    string? AddressLine2,
    string? Town,
    string? County,
    string? Postcode,
    string? Country,
    string? Phone,
    string? Email,
    string? Website,
    string? VatNumber,
    decimal DefaultVatRate,
    string QuotePrefix,
    string InvoicePrefix,
    string? PaymentTerms,
    string? BankName,
    string? BankAccountName,
    string? BankSortCode,
    string? BankAccountNumber,
    string? EmailFooter
);
